/*
 * This source file was generated by the Gradle 'init' task
 */
package utb.fai;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class App {

	public static void main(String[] args) {
		ConcurrentLinkedDeque<URIinfo> foundURIs = new ConcurrentLinkedDeque<>();
		Set<URI> visitedURIs = Collections.synchronizedSet(new HashSet<>());
		
        int maxDepth = Integer.parseInt(args[1]);
		int debugLevel = 0;

        if (args.length >= 3) {
            try {
                debugLevel = Integer.parseInt(args[2]);
            } catch (NumberFormatException ex) {}
        }

		try {
			URI uri = new URI(args[0] + "/");
			foundURIs.add(new URIinfo(uri, 0));
			visitedURIs.add(uri);

			if (args.length < 1) {
				System.err.println("Missing parameter - start URL");
				return;
			}

			// Vytvoření thread poolu v závislosti na počtu jader/vláken procesoru počítače
			int nThreads = Math.max(2, Runtime.getRuntime().availableProcessors());
            ExecutorService executor = Executors.newFixedThreadPool(nThreads);

			while (true) {
				URIinfo uriInfo = foundURIs.pollFirst();

				if (uriInfo == null) {
					if (((ThreadPoolExecutor) executor).getActiveCount() == 0) break;

					try { 
						Thread.sleep(100); 
					} catch (InterruptedException ex) {}

					continue;
				}

				if (uriInfo.depth > maxDepth) continue;

				// Vlastní task používající Jsoup
				executor.submit(new CrawlerTask(uriInfo, foundURIs, visitedURIs, maxDepth, debugLevel));
			}

        executor.shutdown();

        try {
            executor.awaitTermination(10, TimeUnit.MINUTES);
        } catch (InterruptedException e) {
			e.printStackTrace();
        }

        // Print 20 nejčetnějších slov
        WordCounter.getInstance().printTopWords(20);
		} catch (URISyntaxException e) {
			System.err.println("Zachycena neošetřená výjimka, končíme...");
			e.printStackTrace();
		}
	}

}
